INSERT INTO USUARIO (NOMBRE, APELLIDOS, EMAIL, PASSW) 
	VALUES ('Enrique', 'Canadas Cobo', 'enrique@uma.es', '12345678a');

INSERT INTO USUARIO (NOMBRE, APELLIDOS, EMAIL, PASSW) 
	VALUES ('Felipe', 'Llinares Gomez', 'felipe@uma.es', '12345678a');

INSERT INTO USUARIO (NOMBRE, APELLIDOS, EMAIL, PASSW) 
	VALUES ('Jose Maria', 'Tapia Catena', 'josemaria@uma.es', '12345678a');

INSERT INTO USUARIO (NOMBRE, APELLIDOS, EMAIL, PASSW) 
	VALUES ('Pablo', 'Duran Trujillano' 'pablo@uma.es', '12345678a');

INSERT INTO USUARIO (NOMBRE, APELLIDOS, EMAIL, PASSW) 
	VALUES ('Santiago', 'Abascal Conde', 'santi@espana.es', '12345678a');

INSERT INTO USUARIO (NOMBRE, APELLIDOS, EMAIL, PASSW)
	VALUES ('Club', 'Manzano', 'info@clubmanzano.com', '12345678a');

INSERT INTO ACTIVIDAD (FECHA, HORA, TIPO, PLAZAS)
    VALUES ('2022-06-1', '10:00:00', 1, 8);

INSERT INTO RESERVA (ACTIVIDAD, USUARIO)
    VALUES (1, 1);